on: push
name: packtracker.io
env:
  PT_PROJECT_TOKEN: ${{ secrets.PT_PROJECT_TOKEN }}
jobs:
  build:
    name: Create build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install Dependencies
        run: npm install

      - name: Create bundle
        run: npm run build
  report:
    name: report webpack stats
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: report webpack stats
      uses: packtracker/report@2.2.7
      env:
        WEBPACK_CONFIG_PATH: ./webpack.config.js
